version: '3'
services:
  sample-app:
    image: mcr.microsoft.com/devcontainers/typescript-node
    environment:
      LRU_CACHE_MAX_SIZE: 5000
      LRU_CACHE_MAX_ITEM_COUNT: 200
      LRU_CACHE_REDIS_PASSWORD: developer
      LRU_CACHE_REDIS_HOST: redis
      LRU_CACHE_REDIS_PORT: 6379
    volumes:
      - ./SampleApp/:/app
      - ./library/:/library
    command: |
        cd /library/LruCacheProvider && npm install && \
        cd ../../app && npm install && \
        npx ts-node run.ts  

  redis:
    image: 'redis-stack:latest'
    ports:
      - '6379:6379'
    environment:
      REDIS_ARGS: "--requirepass developer"

networks:
  default:
